### ISSUE TITLE
Conflict leftover in component file TheComponentTreeContainer.vue

### ISSUE THREAD

**Issue by chm-dev** [oslabs-beta/birdzeye#29]
Just a friendly reminder about unmerged conflict in 
https://github.com/oslabs-beta/vuety/blob/b2d1a332e1bc67623e0eacfb6cfe6a585d6f04fa/src/components/componentTree/TheComponentTreeContainer.vue#L23-L28

**Comment by Takodakko** [comment]
Thank you for bringing up this issue. It has now been rectified.
